# Generated by Django 5.0.3 on 2024-03-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='game title')),
                ('release_date', models.DateField(verbose_name='release date')),
                ('description', models.TextField(verbose_name='game description')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email address')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('role', models.CharField(choices=[('PL', 'Player'), ('GO', 'Game Owner'), ('AD', 'Admin')], default='PL', max_length=2, verbose_name='user role')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPerformance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('elo_rating', models.IntegerField(default=1000, verbose_name='ELO rating')),
                ('matches_played', models.IntegerField(default=0, verbose_name='matches played')),
                ('matches_won', models.IntegerField(default=0, verbose_name='matches won')),
                ('matches_lost', models.IntegerField(default=0, verbose_name='matches lost')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RankRealm.game', verbose_name='related game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RankRealm.userprofile', verbose_name='player')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('leaderboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RankRealm.game', verbose_name='associated game')),
                ('player_performance', models.ManyToManyField(to='RankRealm.playerperformance', verbose_name='player performances')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RankRealm.userprofile', verbose_name='game developer'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='event name')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RankRealm.game', verbose_name='associated game')),
                ('participants', models.ManyToManyField(to='RankRealm.playerperformance', verbose_name='event participants')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='RankRealm.userprofile', verbose_name='event organizer')),
            ],
        ),
    ]
